### ISSUE TITLE
Transformers commit 

### ISSUE THREAD

**Issue by oplatek** [zhichaoxu-shufe/context-aware-decoding-qfs#1]
Hi!

Thank you for open-sourcing your code.
I want to avoid pitfalls and mismatched versions of the Transformers library and your changes in `generation/utils.py`.

Could you please document which commit of the Transformers library you used for running your code?

Thank you

**Comment by zhichaoxu-shufe** [comment]
hi

It is based on transformers==4.36, but I think later transformer versions will work as well since `generation/utils.py` is fairly untouched in recent transformers version update

**Comment by oplatek** [comment]
Thank you for your quick reply.

I had some issues with the current main branch from transformers but with the `v4.36.2` tag I could run the mistral experiments after minor fixes.

**Comment by zhichaoxu-shufe** [comment]
@oplatek I am closing this issue if you're good. 

Please cite my paper as you see fit. Thanks!
